name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "hello"
          replace: "world"
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: build/central-access-apps/central-access.site
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CENTRAL_ACCESS_SITES_PROD }}'
          target: stage
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: /home/runner/work/central-access-apps/central-access-apps/central-access.site
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CENTRAL_ACCESS_SITES_PROD }}'
          target: prod
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: /home/runner/work/central-access-apps/central-access-apps/stocknews.central-access.site
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CENTRAL_ACCESS_SITES_PROD }}'
          projectId: central-access-sites-prod
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
