name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
#     - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: /home/runner/work/central-access-apps/central-access-apps/central-access.site
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CENTRAL_ACCESS_SITES_PROD }}'
          channelId: live
          projectId: central-access-sites-prod
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: /home/runner/work/central-access-apps/central-access-apps/stocknews.central-access.site
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CENTRAL_ACCESS_SITES_PROD }}'
          channelId: live
          projectId: central-access-sites-prod
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
