name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Step 1 - Create a temporary temp folder
        run: mkdir ./temp

      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          path: ./project

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "hello"
          replace: "world"
          include: "index.html"

      - name: Copy files
        working-directory: ./project
        run: |
          cp -r ./project ./temp
          pwd

      - name: Run pwd in project
        working-directory: ./temp
        run: |
          pwd
          ls -l

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: ./build/central-access-apps/central-access.site
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CENTRAL_ACCESS_SITES_PROD }}'
          channelId: live
          target: stage
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: /home/runner/work/central-access-apps/central-access-apps/central-access.site
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CENTRAL_ACCESS_SITES_PROD }}'
          channelId: live
          target: prod
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: /home/runner/work/central-access-apps/central-access-apps/stocknews.central-access.site
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CENTRAL_ACCESS_SITES_PROD }}'
          channelId: live
          projectId: central-access-sites-prod
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
